// MCP Tool: generate_slg_map — strategy/simulation game map system
// Generates: hex/grid tile map, fog of war, tile interaction, unit placement
import * as fs from "fs";
import * as path from "path";

export interface GenerateSlgMapArgs {
  /** Path to Godot project root */
  project_path: string;
  /** Map name (default: "StrategyMap") */
  name?: string;
  /** Grid type: "hex" (hexagonal) or "square" (square grid) */
  grid_type?: "hex" | "square";
  /** Map width in tiles (default: 20) */
  width?: number;
  /** Map height in tiles (default: 20) */
  height?: number;
  /** Tile size in pixels (default: 64 for hex, 32 for square) */
  tile_size?: number;
  /** Include fog of war (default: true) */
  fog_of_war?: boolean;
  /** Include tile interaction system (default: true) */
  interaction?: boolean;
  /** Include turn system (default: true) */
  turn_system?: boolean;
}

/**
 * Generate a complete strategy/simulation game map system.
 * Features: hex/grid tiles, fog of war, tile interaction, unit placement, turn system.
 */
export function generateSlgMap(args: GenerateSlgMapArgs): string {
  const {
    project_path, name = "StrategyMap", grid_type = "hex",
    width = 20, height = 20, tile_size,
    fog_of_war = true, interaction = true, turn_system = true,
  } = args;

  if (!project_path) throw new Error("project_path is required");
  if (!fs.existsSync(project_path)) throw new Error(`Project path not found: ${project_path}`);

  const ts = tile_size || (grid_type === "hex" ? 64 : 32);
  const scriptDir = path.join(project_path, "scripts", "slg");
  const sceneDir = path.join(project_path, "scenes", "slg");
  if (!fs.existsSync(scriptDir)) fs.mkdirSync(scriptDir, { recursive: true });
  if (!fs.existsSync(sceneDir)) fs.mkdirSync(sceneDir, { recursive: true });

  // ── 1. Tile definition ──
  const tileGd = [
    `# SLG Tile — single hex/square tile on the strategy map`,
    `class_name SLGTile`,
    `extends Node2D`,
    ``,
    `signal tile_clicked(tile: SLGTile)`,
    `signal tile_hovered(tile: SLGTile)`,
    ``,
    `@export var grid_pos: Vector2i = Vector2i.ZERO`,
    `@export var tile_type: String = "plains"  # plains, forest, mountain, water, desert, city`,
    `@export var movement_cost: int = 1`,
    `@export var defense_bonus: int = 0`,
    `@export var is_walkable: bool = true`,
    `@export var is_occupied: bool = false`,
    `@export var owner_id: int = -1  # -1 = neutral`,
    ``,
    `var fog_of_war_state: int = 0  # 0=hidden, 1=revealed, 2=visible`,
    `var highlight_state: String = ""  # "none", "move", "attack", "selected"`,
    ``,
    `@onready var _sprite: Sprite2D = $Sprite2D`,
    `@onready var _highlight: Sprite2D = $Highlight`,
    `@onready var _fog: Sprite2D = $FogOfWar`,
    ``,
    `func _ready() -> void:`,
    `\t_update_visual()`,
    ``,
    `func init(pos: Vector2i, type: String) -> void:`,
    `\tgrid_pos = pos`,
    `\ttile_type = type`,
    `\t_set_tile_properties(type)`,
    `\t_update_visual()`,
    ``,
    `func _set_tile_properties(type: String) -> void:`,
    `\tmatch type:`,
    `\t\t"plains": movement_cost = 1; defense_bonus = 0; is_walkable = true`,
    `\t\t"forest": movement_cost = 2; defense_bonus = 2; is_walkable = true`,
    `\t\t"mountain": movement_cost = 3; defense_bonus = 4; is_walkable = false`,
    `\t\t"water": movement_cost = 99; defense_bonus = 0; is_walkable = false`,
    `\t\t"desert": movement_cost = 2; defense_bonus = 0; is_walkable = true`,
    `\t\t"city": movement_cost = 1; defense_bonus = 1; is_walkable = true`,
    ``,
    `func set_highlight(state: String) -> void:`,
    `\thighlight_state = state`,
    `\t_update_highlight()`,
    ``,
    `func set_fog_state(state: int) -> void:`,
    `\tfog_of_war_state = state`,
    `\t_update_fog()`,
    ``,
    `func _update_visual() -> void:`,
    `\tif _sprite:`,
    `\t\t# Set tile texture based on type`,
    `\t\t# _sprite.texture = load("res://assets/tiles/" + tile_type + ".png")`,
    `\t\tpass`,
    ``,
    `func _update_highlight() -> void:`,
    `\tif not _highlight: return`,
    `\tmatch highlight_state:`,
    `\t\t"none": _highlight.modulate = Color.TRANSPARENT`,
    `\t\t"move": _highlight.modulate = Color(0, 0.5, 1, 0.3)`,
    `\t\t"attack": _highlight.modulate = Color(1, 0, 0, 0.3)`,
    `\t\t"selected": _highlight.modulate = Color(1, 1, 0, 0.3)`,
    ``,
    `func _update_fog() -> void:`,
    `\tif not _fog: return`,
    `\tmatch fog_of_war_state:`,
    `\t\t0: _fog.modulate = Color(0, 0, 0, 1)   # hidden`,
    `\t\t1: _fog.modulate = Color(0, 0, 0, 0.5) # revealed (dim)`,
    `\t\t2: _fog.modulate = Color.TRANSPARENT    # visible`,
    ``,
    `func _input_event(_viewport: Node, event: InputEvent, _shape_idx: int) -> void:`,
    `\tif event is InputEventMouseButton and event.pressed and event.button_index == MOUSE_BUTTON_LEFT:`,
    `\t\ttile_clicked.emit(self)`,
    `\tif event is InputEventMouseMotion:`,
    `\t\ttile_hovered.emit(self)`,
    ``,
  ].join("\n");
  fs.writeFileSync(path.join(scriptDir, "slg_tile.gd"), tileGd, "utf-8");

  // ── 2. Hex / Grid map generator ──
  const gridGd = [
    `# SLG Grid — hex/square grid generator and manager`,
    `class_name SLGGrid`,
    `extends Node2D`,
    ``,
    `signal tile_selected(tile: SLGTile)`,
    `signal movement_confirmed(path: Array[SLGTile])`,
    ``,
    `@export var grid_type: String = "${grid_type}"`,
    `@export var map_width: int = ${width}`,
    `@export var map_height: int = ${height}`,
    `@export var tile_size: float = ${ts}`,
    ``,
    `var tiles: Dictionary = {}  # Vector2i -> SLGTile`,
    `var _selected_tile: SLGTile = null`,
    `var _highlighted_tiles: Array[SLGTile] = []`,
    ``,
    `func _ready() -> void:`,
    `\t_generate_map()`,
    ``,
    `func _generate_map() -> void:`,
    `\tfor x in range(map_width):`,
    `\t\tfor y in range(map_height):`,
    `\t\t\t_create_tile(Vector2i(x, y))`,
    ``,
    `func _create_tile(pos: Vector2i) -> void:`,
    `\tvar tile_scene := preload("res://scripts/slg/slg_tile.gd")`,
    `\tvar tile := SLGTile.new()`,
    `\ttile.name = "Tile_" + str(pos.x) + "_" + str(pos.y)`,
    ``,
    `\t# Position`,
    `\tvar world_pos := grid_to_world(pos)`,
    `\ttile.position = world_pos`,
    `\ttile.init(pos, _get_tile_type(pos))`,
    `\ttile.tile_clicked.connect(_on_tile_clicked)`,
    `\tadd_child(tile)`,
    `\ttiles[pos] = tile`,
    ``,
    `func grid_to_world(pos: Vector2i) -> Vector2:`,
    `\tif grid_type == "hex":`,
    `\t\tvar x := pos.x * tile_size * 1.5`,
    `\t\tvar y := pos.y * tile_size * 1.732 + (int(pos.x) % 2) * tile_size * 0.866`,
    `\t\treturn Vector2(x, y)`,
    `\telse:`,
    `\t\treturn Vector2(pos.x * tile_size, pos.y * tile_size)`,
    ``,
    `func world_to_grid(world_pos: Vector2) -> Vector2i:`,
    `\tif grid_type == "hex":`,
    `\t\t# Approximate hex grid position from world coords`,
    `\t\tvar x := int(world_pos.x / (tile_size * 1.5))`,
    `\t\tvar y := int((world_pos.y - (x % 2) * tile_size * 0.866) / (tile_size * 1.732))`,
    `\t\treturn Vector2i(x, y)`,
    `\telse:`,
    `\t\treturn Vector2i(int(world_pos.x / tile_size), int(world_pos.y / tile_size))`,
    ``,
    `func get_neighbors(pos: Vector2i) -> Array[Vector2i]:`,
    `\tvar neighbors: Array[Vector2i] = []`,
    `\tif grid_type == "hex":`,
    `\t\t# Hex neighbors (6 directions)`,
    `\t\tvar parity := pos.x % 2`,
    `\t\tvar dirs := [`,
    `\t\t\t[Vector2i(1, 0), Vector2i(-1, 0), Vector2i(0, -1), Vector2i(1, -1), Vector2i(0, 1), Vector2i(1, 1)],`,
    `\t\t\t[Vector2i(1, 0), Vector2i(-1, 0), Vector2i(-1, -1), Vector2i(0, -1), Vector2i(-1, 1), Vector2i(0, 1)],`,
    `\t\t][parity]`,
    `\t\tfor d in dirs:`,
    `\t\t\tvar n := pos + d`,
    `\t\t\tif tiles.has(n): neighbors.append(n)`,
    `\telse:`,
    `\t\t# Square neighbors (4 or 8 directions)`,
    `\t\tfor dx in range(-1, 2):`,
    `\t\t\tfor dy in range(-1, 2):`,
    `\t\t\t\tif dx == 0 and dy == 0: continue`,
    `\t\t\t\tvar n := Vector2i(pos.x + dx, pos.y + dy)`,
    `\t\t\t\tif tiles.has(n): neighbors.append(n)`,
    `\treturn neighbors`,
    ``,
    `func find_path(from: Vector2i, to: Vector2i) -> Array[SLGTile]:`,
    `\t# A* pathfinding`,
    `\tvar open_set: Array[Vector2i] = [from]`,
    `\tvar came_from: Dictionary = {}`,
    `\tvar g_score: Dictionary = {}`,
    `\tvar f_score: Dictionary = {}`,
    `\tg_score[from] = 0`,
    `\tf_score[from] = _heuristic(from, to)`,
    `\t`,
    `\twhile open_set.size() > 0:`,
    `\t\t# Get lowest f_score`,
    `\t\tvar current := open_set[0]`,
    `\t\tvar current_f := f_score.get(current, 99999)`,
    `\t\tfor pos in open_set:`,
    `\t\t\tvar f := f_score.get(pos, 99999)`,
    `\t\t\tif f < current_f:`,
    `\t\t\t\tcurrent = pos`,
    `\t\t\t\tcurrent_f = f`,
    `\t\t`,
    `\t\tif current == to:`,
    `\t\t\treturn _reconstruct_path(came_from, current)`,
    `\t\t`,
    `\t\topen_set.erase(current)`,
    `\t\tfor neighbor in get_neighbors(current):`,
    `\t\t\tvar tile := tiles[neighbor] as SLGTile`,
    `\t\t\tif not tile.is_walkable: continue`,
    `\t\t\tvar tentative_g := g_score.get(current, 99999) + tile.movement_cost`,
    `\t\t\tif tentative_g < g_score.get(neighbor, 99999):`,
    `\t\t\t\tcame_from[neighbor] = current`,
    `\t\t\t\tg_score[neighbor] = tentative_g`,
    `\t\t\t\tf_score[neighbor] = tentative_g + _heuristic(neighbor, to)`,
    `\t\t\t\tif not neighbor in open_set:`,
    `\t\t\t\t\topen_set.append(neighbor)`,
    `\treturn []  # No path found`,
    ``,
    `func _heuristic(a: Vector2i, b: Vector2i) -> float:`,
    `\treturn abs(a.x - b.x) + abs(a.y - b.y)`,
    ``,
    `func _reconstruct_path(came_from: Dictionary, current: Vector2i) -> Array[SLGTile]:`,
    `\tvar path: Array[SLGTile] = []`,
    `\tvar pos := current`,
    `\twhile came_from.has(pos):`,
    `\t\tpath.append(tiles[pos])`,
    `\t\tpos = came_from[pos]`,
    `\tpath.reverse()`,
    `\treturn path`,
    ``,
    `func _get_tile_type(pos: Vector2i) -> String:`,
    `\t# Simple noise-based terrain generation`,
    `\tvar n := sin(pos.x * 12.9898 + pos.y * 78.233) * 43758.5453`,
    `\tvar val := n - floor(n)`,
    `\tif val < 0.1: return "water"`,
    `\tif val < 0.2: return "mountain"`,
    `\tif val < 0.4: return "forest"`,
    `\tif val < 0.6: return "desert"`,
    `\tif val < 0.8: return "plains"`,
    `\treturn "city"`,
    ``,
    `func _on_tile_clicked(tile: SLGTile) -> void:`,
    `\t_selected_tile = tile`,
    `\ttile_selected.emit(tile)`,
    ``,
    `func show_movement_range(from: Vector2i, range: int) -> void:`,
    `\t# Clear old highlights`,
    `\tfor t in _highlighted_tiles:`,
    `\t\tt.set_highlight("none")`,
    `\t_highlighted_tiles.clear()`,
    `\t`,
    `\t# BFS to find tiles within movement range`,
    `\tvar frontier: Array[Vector2i] = [from]`,
    `\tvar cost: Dictionary = {from: 0}`,
    `\twhile frontier.size() > 0:`,
    `\t\tvar current := frontier.pop_front()`,
    `\t\tfor neighbor in get_neighbors(current):`,
    `\t\t\tvar tile := tiles[neighbor] as SLGTile`,
    `\t\t\tif not tile.is_walkable: continue`,
    `\t\t\tvar new_cost := cost[current] + tile.movement_cost`,
    `\t\t\tif new_cost <= range and (not cost.has(neighbor) or new_cost < cost[neighbor]):`,
    `\t\t\t\tcost[neighbor] = new_cost`,
    `\t\t\t\tfrontier.append(neighbor)`,
    `\t\t\t\ttile.set_highlight("move")`,
    `\t\t\t\t_highlighted_tiles.append(tile)`,
    ``,
  ].join("\n");
  fs.writeFileSync(path.join(scriptDir, "slg_grid.gd"), gridGd, "utf-8");

  // ── 3. Fog of war ──
  if (fog_of_war) {
    const fogGd = [
      `# Fog of War System — visibility, exploration, and map reveal`,
      `class_name FogOfWar`,
      `extends Node`,
      ``,
      `@export var vision_range: int = 4  # tiles`,
      `@export var grid: SLGGrid = null`,
      `@export var reveal_on_start: bool = true`,
      ``,
      `func _ready() -> void:`,
      `\tif not grid:`,
      `\t\tgrid = get_parent().find_child("SLGGrid") as SLGGrid`,
      ``,
      `func reveal_around(pos: Vector2i, range: int = -1) -> void:`,
      `\tvar r := range if range >= 0 else vision_range`,
      `\tfor x in range(-r, r + 1):`,
      `\t\tfor y in range(-r, r + 1):`,
      `\t\t\tvar tile_pos := Vector2i(pos.x + x, pos.y + y)`,
      `\t\t\tif grid and grid.tiles.has(tile_pos):`,
      `\t\t\t\tvar tile := grid.tiles[tile_pos] as SLGTile`,
      `\t\t\t\tvar dist := abs(x) + abs(y)`,
      `\t\t\t\tif dist <= r:`,
      `\t\t\t\t\ttile.set_fog_state(2)  # visible`,
      `\t\t\t\telif dist <= r * 1.5:`,
      `\t\t\t\t\ttile.set_fog_state(1)  # revealed (dim)`,
      `\t\t\t\telse:`,
      `\t\t\t\t\ttile.set_fog_state(0)  # hidden`,
      ``,
      `func reveal_all() -> void:`,
      `\tif not grid: return`,
      `\tfor tile in grid.tiles.values():`,
      `\t\t(tile as SLGTile).set_fog_state(2)`,
      ``,
      `func hide_all() -> void:`,
      `\tif not grid: return`,
      `\tfor tile in grid.tiles.values():`,
      `\t\t(tile as SLGTile).set_fog_state(0)`,
      ``,
    ].join("\n");
    fs.writeFileSync(path.join(scriptDir, "fog_of_war.gd"), fogGd, "utf-8");
  }

  // ── 4. Turn system ──
  if (turn_system) {
    const turnGd = [
      `# Turn System — turn-based strategy game loop`,
      `class_name TurnSystem`,
      `extends Node`,
      ``,
      `signal turn_started(turn_number: int, faction: String)`,
      `signal turn_ended(turn_number: int, faction: String)`,
      `signal all_factions_done(turn_number: int)`,
      ``,
      `@export var factions: Array[String] = ["Player", "AI_Enemy", "AI_Neutral"]`,
      `@export var player_faction: String = "Player"`,
      ``,
      `var current_turn: int = 1`,
      `var current_faction_index: int = 0`,
      `var is_processing: bool = false`,
      ``,
      `func start_game() -> void:`,
      `\tcurrent_turn = 1`,
      `\tcurrent_faction_index = 0`,
      `\t_begin_turn()`,
      ``,
      `func end_turn() -> void:`,
      `\tif is_processing: return`,
      `\t`,
      `\tturn_ended.emit(current_turn, factions[current_faction_index])`,
      `\t`,
      `\tcurrent_faction_index += 1`,
      `\tif current_faction_index >= factions.size():`,
      `\t\tcurrent_faction_index = 0`,
      `\t\tcurrent_turn += 1`,
      `\t\tall_factions_done.emit(current_turn)`,
      `\t`,
      `\t_begin_turn()`,
      ``,
      `func _begin_turn() -> void:`,
      `\tvar faction := factions[current_faction_index]`,
      `\tturn_started.emit(current_turn, faction)`,
      ``,
      `func get_current_faction() -> String:`,
      `\treturn factions[current_faction_index]`,
      ``,
      `func is_player_turn() -> bool:`,
      `\treturn factions[current_faction_index] == player_faction`,
      ``,
    ].join("\n");
    fs.writeFileSync(path.join(scriptDir, "turn_system.gd"), turnGd, "utf-8");
  }

  // ── 5. Main map scene ──
  const mapScenePath = path.join(sceneDir, `${name}.tscn`);
  const mainGd = [
    `extends Node2D`,
    ``,
    `# ${name} — Strategy map controller`,
    ``,
    `@onready var grid: SLGGrid = $SLGGrid`,
    `@onready var camera: Camera2D = $Camera2D`,
    `@onready var turn_system: TurnSystem = $TurnSystem`,
    `${fog_of_war ? "@onready var fog: FogOfWar = $FogOfWar" : ""}`,
    ``,
    `func _ready() -> void:`,
    `\tgrid.tile_selected.connect(_on_tile_selected)`,
    `${turn_system ? "\tturn_system.start_game()" : ""}`,
    ``,
    `func _on_tile_selected(tile: SLGTile) -> void:`,
    `\tprint("Selected: ", tile.grid_pos, " (", tile.tile_type, ")")`,
    `\tgrid.show_movement_range(tile.grid_pos, ${turn_system ? "4" : "0"})`,
    `\t`,
    `${fog_of_war ? "\t# Reveal fog around selected tile" : ""}`,
    `${fog_of_war ? "\tfog.reveal_around(tile.grid_pos)" : ""}`,
    ``,
  ].join("\n");
  fs.writeFileSync(path.join(sceneDir, `${name}_controller.gd`), mainGd, "utf-8");

  // Write main scene
  const mapScene = [
    `[gd_scene load_steps=1 format=3]`,
    ``,
    `[node name="${name}" type="Node2D"]`,
    `script = ExtResource("1")`,
    ``,
    `[node name="Camera2D" type="Camera2D" parent="."]`,
    ``,
    `[node name="SLGGrid" type="Node2D" parent="."]`,
    `script = ExtResource("2")`,
    ``,
    `[node name="TurnSystem" type="Node" parent="."]`,
    `${turn_system ? 'script = ExtResource("3")' : ""}`,
    ``,
  ].join("\n");
  fs.writeFileSync(mapScenePath, mapScene, "utf-8");

  return [
    `Generated Strategy Map System — SLG-style hex/grid map`,
    ``,
    `Map: ${width}x${height} ${grid_type} tiles (${width * height} total)`,
    `Tile size: ${ts}px`,
    ``,
    `Files:`,
    `  scripts/slg/slg_tile.gd      — Individual tile (type, fog, highlight, input)`,
    `  scripts/slg/slg_grid.gd       — Grid manager (generation, A* pathfinding, movement range)`,
    `${fog_of_war ? "  scripts/slg/fog_of_war.gd   — Fog of war (reveal/hide/explore)" : ""}`,
    `${turn_system ? "  scripts/slg/turn_system.gd   — Turn-based game loop" : ""}`,
    `  scenes/slg/${name}.tscn       — Main map scene`,
    `  scenes/slg/${name}_controller.gd — Map controller`,
    ``,
    `Terrain types: plains, forest, mountain, water, desert, city`,
    `(Each with different movement costs and defense bonuses)`,
    ``,
    `Features:`,
    `  ${grid_type === "hex" ? "Hexagonal" : "Square"} grid layout`,
    `  A* pathfinding with terrain cost`,
    `  Movement range highlighting`,
    `  Fog of war (3 states: hidden/revealed/visible)`,
    `  Turn-based faction system`,
    `  Click-to-select tile interaction`,
    ``,
    `Setup:`,
    `  1. Add SLGGrid to your scene`,
    `  2. Add FogOfWar for visibility system`,
    `  3. Add TurnSystem for turn management`,
    `  4. Create tile textures in assets/tiles/`,
    `  5. Add unit sprites on top of tiles`,
  ].join("\n");
}
