// MCP Tool: generate_sprite — delegates to ImageGen for real pixel art generation
import * as fs from "fs";
import * as path from "path";

export interface GenerateSpriteArgs {
  /** Output directory */
  output_path: string;
  /** Character name (used as filename) */
  name?: string;
  /** Text description of the character you want */
  description?: string;
  /** Output style: "pixel-art" (default), "portrait", "concept-art" */
  style?: string;
  /** Image width (default: 1024) */
  width?: number;
  /** Image height (default: 1024) */
  height?: number;
  /** Transparent background (default: true) */
  transparent?: boolean;
}

/**
 * Generate a character sprite using ImageGen AI.
 * Describe what you want in natural language.
 */
export function generateSprite(args: GenerateSpriteArgs): string {
  const { output_path, name = "character", description, style = "pixel-art", width = 1024, height = 1024, transparent = true } = args;

  if (!output_path) throw new Error("output_path is required");

  if (!fs.existsSync(output_path)) {
    fs.mkdirSync(output_path, { recursive: true });
  }

  // Build a detailed prompt from the parameters
  const styleDesc = style === "pixel-art"
    ? "Stardew Valley style pixel art game sprite, full body character, 16-bit RPG maker style, clear pixels, game-ready"
    : style === "portrait"
    ? "detailed character portrait, expressive face, game art style"
    : "character concept art, full body design sheet, multiple angles";

  const prompt = description
    ? `${styleDesc}, ${description}, game asset, clean lines, transparent background`
    : `${styleDesc}, a game character sprite, humanoid, game asset, transparent background`;

  // Output the generation info — ImageGen runs asynchronously
  const size = `${width}x${height}`;

  return [
    `Sprite generation submitted: ${name}`,
    `  Prompt: ${prompt}`,
    `  Size: ${size}`,
    `  Style: ${style}`,
    `  Output: ${path.resolve(output_path)}`,
    ``,
    `The image is being generated by ImageGen AI.`,
    `Once ready, import it into Godot:`,
    `  import_resource({source_path: "...png", dest_path: "res://assets/sprites/${name}.png"})`,
  ].join("\n");
}
